set tabstop=2
set nowrap
set number
set smartindent
set smarttab
set expandtab
set autoindent

set shiftwidth=2 
colorscheme koehler 
set background=dark
syntax on
nmap <F8> :TagbarToggle<CR>
nmap <F7> :NERDTree<CR>

filetype plugin indent on
set ofu=syntaxcomplete#Complete
